/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/circle/[id]/board` | `/circle/[id]/board`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/circle/[id]` | `/circle/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/circle/[id]/new-pin` | `/circle/[id]/new-pin`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/circle/[id]/settings` | `/circle/[id]/settings`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/event/[id]` | `/event/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/circle/[id]/board` | `/circle/[id]/board`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(app)'}/circle/[id]` | `/circle/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(app)'}/circle/[id]/new-pin` | `/circle/[id]/new-pin`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(app)'}/circle/[id]/settings` | `/circle/[id]/settings`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(app)'}/event/[id]` | `/event/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | `${'/(app)'}/circle/${Router.SingleRoutePart<T>}/board${`?${string}` | `#${string}` | ''}` | `/circle/${Router.SingleRoutePart<T>}/board${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/circle/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/circle/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/circle/${Router.SingleRoutePart<T>}/new-pin${`?${string}` | `#${string}` | ''}` | `/circle/${Router.SingleRoutePart<T>}/new-pin${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/circle/${Router.SingleRoutePart<T>}/settings${`?${string}` | `#${string}` | ''}` | `/circle/${Router.SingleRoutePart<T>}/settings${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/event/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/event/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(app)'}/circle/[id]/board` | `/circle/[id]/board`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/circle/[id]` | `/circle/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/circle/[id]/new-pin` | `/circle/[id]/new-pin`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/circle/[id]/settings` | `/circle/[id]/settings`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/event/[id]` | `/event/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
